version: '3.8'

services:
  swarm-visualizer:
    image: swarm-visualizer:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLUSTER_NAME=Local Swarm
      # - ROOT_CONTEXT=/testing
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/static:/static
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: always
